name: 'GitHub Container Registry Login'
runs:
  using: "composite"
  steps:
    - name: Checkout backend
      uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
